name: inventario_cea_va
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  anim_search_bar: ^2.0.3
  animated_splash_screen: ^1.3.0
  date_format: ^2.0.7
  flutter:
    sdk: flutter
  flutter_expanded_tile: ^0.3.7
  flutter_riverpod: ^2.4.3
  google_fonts: ^6.1.0
  graphql_flutter: ^5.2.0-beta.5
  jwt_decoder: ^2.0.1
  line_icons: ^2.0.3
  page_transition: ^2.1.0
  path_provider: ^2.1.1
  pdf: ^3.10.6
  roundcheckbox: ^2.0.5
  syncfusion_flutter_pdfviewer: ^23.1.39

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
